Repository BPLA-Team/locus_no_pilotus, pull requests merged in 2024-03, with the labels that each got.

#16 fix some mistakes in written gui classes
  gui/base.h
  gui/hill.cpp
  gui/hill.h
  gui/target.cpp
  gui/target.h
  gui/trajectory.h
  gui/trappy_circle.cpp
  gui/trappy_circle.h
  gui/trappy_line.cpp
  gui/trappy_line.h
  lib/base.h
  lib/hill.h
  lib/point.h
  lib/target.cpp
  lib/target.h
  lib/trajectory.h
  lib/trappy_circle.h
  lib/trappy_line.cpp
  lib/trappy_line.h
  tests/target_test.cpp
  tests/target_test.h
Labels: mistakefix

#20 create LICENSE
  LICENSE
Labels: documentation

#21 massive gui update
  Backend/CMakeLists.txt
  CMakeLists.txt
  gui/CMakeLists.txt
  gui/hill.cpp
  gui/hill.h
  gui/target.h
  gui/trappy_circle.cpp
  gui/trappy_circle.h
  gui/trappy_line.h
  images/icon.png
  lib/CMakeLists.txt
  lib/hill.cpp
  lib/hill.h
  lib/point.h
  lib/target.h
  lib/trappy_circle.h
  lib/trappy_line.h
  main/CMakeLists.txt
  main/add_objects_forms/add_target_form.cpp
  main/add_objects_forms/add_target_form.h
  main/add_objects_forms/add_target_form.ui
  main/add_objects_forms/add_trappy_circle_form.cpp
  main/add_objects_forms/add_trappy_circle_form.h
  main/add_objects_forms/add_trappy_circle_form.ui
  main/add_objects_forms/add_trappy_line_form.cpp
  main/add_objects_forms/add_trappy_line_form.h
  main/add_objects_forms/add_trappy_line_form.ui
  main/main.cpp
  main/mainwindow.cpp
  main/mainwindow.h
  main/mainwindow.ui
  main/mainwindow_connections.cpp
  main/plot_manager/plot_manager.cpp
  main/plot_manager/plot_manager.h
  tests/CMakeLists.txt
  tests/target_test.cpp
Labels: enhancement, mistakefix, preparing

#22 small fixes in gui
  Backend/CMakeLists.txt
  CMakeLists.txt
  gui/CMakeLists.txt
  gui/base.h
  gui/hill.h
  gui/target.h
  gui/trappy_circle.h
  gui/trappy_line.h
  lib/CMakeLists.txt
  lib/hill.h
  lib/target.h
  lib/trappy_circle.h
  lib/trappy_line.h
  main/CMakeLists.txt
  main/add_objects_forms/add_target_form.cpp
  main/add_objects_forms/add_target_form.h
  main/add_objects_forms/add_target_form.ui
  main/add_objects_forms/add_trappy_circle_form.cpp
  main/add_objects_forms/add_trappy_circle_form.h
  main/add_objects_forms/add_trappy_circle_form.ui
  main/add_objects_forms/add_trappy_line_form.cpp
  main/add_objects_forms/add_trappy_line_form.h
  main/add_objects_forms/add_trappy_line_form.ui
  main/plot_manager/plot_manager.h
  tests/CMakeLists.txt
Labels: mistakefix

#23 modify CMake and try some git features
  .gitignore
  Backend/CMakeLists.txt
  CMakeLists.txt
  cmake_paths.cmake
  cmake_scripts/scripts_for_icecream_cpp.cmake
  cmake_scripts/scripts_for_vscode.cmake
  gui/CMakeLists.txt
  lib/CMakeLists.txt
  main/CMakeLists.txt
  main/mainwindow.cpp
  tests/CMakeLists.txt
Labels: enhancement, preparing, extra

#25 TSP class
  Backend/adjacency_matrix.cpp
  Backend/adjacency_matrix.h
  Backend/travelling_salesmans_problem.cpp
  Backend/travelling_salesmans_problem.h
  Backend/tspgraph.h
  tests/matrix_test.cpp
Labels: enhancement, mistakefix, preparing, backend (math)
